CODE: 8614ef642a4ce4 - Command: commands_usage - Guild: 538366293921759233 - Time: 2019-10-26 20:43:26.162820
Traceback (most recent call last):

  File "/home/style/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)

  File "/home/style/PycharmProjects/Rosie/Bot2/cogs/owner.py", line 55, in commands_usage
    plt.clf()

AttributeError: module 'matplotlib' has no attribute 'clf'



CODE: e276881cc92d53 - Command: commands_usage - Guild: 538366293921759233 - Time: 2019-10-26 20:44:08.284785
Traceback (most recent call last):

  File "/home/style/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)

  File "/home/style/PycharmProjects/Rosie/Bot2/cogs/owner.py", line 63, in commands_usage
    plt.xticks(rotation=90)

  File "/home/style/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)

  File "/home/style/.local/lib/python3.6/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)

  File "/home/style/.local/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 88, in print_figure
    super().print_figure(*args, **kwargs)

  File "/home/style/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
    **kwargs)

  File "/home/style/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:

  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)

FileNotFoundError: [Errno 2] No such file or directory: 'img/usage.png'



